'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const calmCode=fs.readFileSync('hpr/edge/ui/edge-calm-ui.js','utf8');
const patchCode=fs.readFileSync('hpr/edge/ui/edge-ui-patch.js','utf8');
function MapMock(){this.added=[]}
MapMock.prototype.addLayer=function(layer,before){this.added.push([layer,before]);return this};
const window={maplibregl:{Map:MapMock}};
const document={addEventListener:()=>{},querySelector:()=>null,querySelectorAll:()=>[],head:{appendChild:()=>{}},createElement:()=>({})};
const context={window,document,console,Object,Array,Map,JSON,performance:{now:()=>0},setInterval:()=>1,clearInterval:()=>{},MutationObserver:function(){},queueMicrotask:()=>{},sessionStorage:{getItem:()=>null,setItem:()=>{}},fetch:async()=>({ok:false})};
vm.createContext(context);vm.runInContext(calmCode,context,{filename:'edge-calm-ui.js'});
assert(window.HPREdgeCalm,'calm UI export missing');
assert.strictEqual(window.HPREdgeCalm.tableRefreshMs,2500);
const m=new window.maplibregl.Map();
m.addLayer({id:'aircraft-selected-emphasis',type:'symbol'});
assert.strictEqual(m.added.length,0,'selected shadow layer must be suppressed');
m.addLayer({id:'aircraft-symbol',layout:{'icon-size':1}});
assert.strictEqual(m.added.length,1,'aircraft symbol should be added');
const expr=m.added[0][0].layout['icon-size'];
assert.strictEqual(expr[0],'interpolate','selected marker must use one top-level zoom interpolation');
function countZoomBased(node){if(!Array.isArray(node))return 0;let n=0;if((node[0]==='interpolate'||node[0]==='step')&&Array.isArray(node[2])&&node[2][0]==='zoom')n++;for(const child of node)n+=countZoomBased(child);return n}
assert.strictEqual(countZoomBased(expr),1,'MapLibre allows only one zoom-based step/interpolate subexpression');
m.addLayer({id:'aircraft-label',paint:{'text-color':'#fff'}});
assert.strictEqual(m.added[1][0].paint['text-color'][0],'case','selected label must use accent expression');
vm.runInContext(patchCode,context,{filename:'edge-ui-patch.js'});
assert(window.HPREdgeMeta,'metadata patch export missing');
const sample='<div class="detail-head"><span class="plane-big" style="--hdg:90deg"><svg>plane</svg></span><span class="detail-title"><b>HVN123</b><small>VN-A123 · A321</small></span></div><div class="section"><div class="kv"><span>ICAO</span><span>888123</span></div></div>';
const out=window.HPREdgeMeta.transformDetailHtml(sample);
assert(out.includes('/flags/4x3/vn.svg'),'Vietnam flag must be in initial detail render');
assert(!out.includes('<svg>plane</svg>'),'detail head aircraft icon must be replaced by flag');
assert(out.includes('Viet Nam'),'country must be stable in initial subtitle');
console.log('edge calm/flag runtime smoke PASS');
