'use strict';
const {test,expect,chromium}=require('@playwright/test');
const http=require('http'),fs=require('fs'),path=require('path');
const ROOT=path.resolve(__dirname,'../hpr/edge/ui');let server,baseURL;
const TRACE=[{ts:1000,lat:20,lon:106,alt:10000,gs:240,track:90},{ts:1060,lat:20.1,lon:106.1,alt:10500,gs:245,track:91},{ts:1120,lat:20.2,lon:106.2,alt:11000,gs:250,track:92}];
const BOOT=`(()=>{globalThis.__replayLoads=0;const sources=new Map(),layers=new Map();globalThis.HPREdgeMap={getSource:id=>sources.get(id),addSource:(id,s)=>sources.set(id,{data:s.data,setData(d){this.data=d}}),getLayer:id=>layers.get(id),addLayer:(l,before)=>layers.set(l.id,{...l,before})};globalThis.HPREdgeTrace={_test:{loadBestTrace:async id=>{globalThis.__replayLoads++;return{kind:'recent',points:${JSON.stringify(TRACE)}}}}};})();`;
test.beforeAll(async()=>{server=http.createServer((req,res)=>{if(req.url==='/edge-g10-replay.js'){res.setHeader('content-type','application/javascript; charset=utf-8');return res.end(fs.readFileSync(path.join(ROOT,'edge-g10-replay.js')))}res.setHeader('content-type','text/html; charset=utf-8');res.end(`<!doctype html><html><head><style>:root{--list:292px;--border:#ccd;--solid:#fff;--shadow:none;--accent:#067;--muted:#789;--text:#123;--s2:#eef}#collection{position:fixed;left:86px;top:50px;width:var(--list);height:300px}</style><script>${BOOT}</script><script src="/edge-g10-replay.js"></script></head><body><div id="collection"></div><div id="detailBody"></div></body></html>`)});await new Promise(r=>server.listen(0,'127.0.0.1',r));baseURL=`http://127.0.0.1:${server.address().port}`});
test.afterAll(async()=>{if(server)await new Promise(r=>server.close(r))});
test('G10 replay is explicit, compact, and does not overlap LOCAL AIRCRAFT',async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome',args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1280,height:800}});const errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto(baseURL,{waitUntil:'domcontentloaded'});await expect(page.locator('#hprReplayDock')).toBeHidden();await page.evaluate(()=>{document.getElementById('detailBody').innerHTML='<div class="hpr-detail-status"><b>LIVE</b></div><div class="section"><div class="kv"><span>ICAO</span><span>888001</span></div></div>'});await expect(page.locator('.hpr-replay-open')).toHaveText('Replay');expect(await page.evaluate(()=>globalThis.__replayLoads)).toBe(0);await page.evaluate(()=>{document.getElementById('detailBody').innerHTML='<div class="hpr-detail-status"><b>LIVE</b></div><div class="section"><div class="kv"><span>ICAO</span><span>888001</span></div></div>'});expect(await page.evaluate(()=>globalThis.__replayLoads)).toBe(0);await page.locator('.hpr-replay-open').click();await expect(page.locator('#hprReplayDock')).toBeVisible();await expect.poll(()=>page.evaluate(()=>globalThis.__replayLoads)).toBe(1);const state=await page.evaluate(()=>({state:window.HPREdgeReplay.state(),range:{max:document.getElementById('hprReplayRange').max,value:document.getElementById('hprReplayRange').value},source:window.HPREdgeMap.getSource('hpr-readsb-replay').data,dock:document.getElementById('hprReplayDock').getBoundingClientRect(),list:document.getElementById('collection').getBoundingClientRect()}));expect(state.state.open).toBe(true);expect(state.state.points).toBe(3);expect(state.state.activeId).toBe('888001');expect(state.range).toEqual({max:'2',value:'2'});expect(state.source.features).toHaveLength(1);expect(state.source.features[0].geometry.coordinates).toEqual([106.2,20.2]);expect(state.dock.left).toBeGreaterThanOrEqual(state.list.right+12);await page.evaluate(()=>{document.getElementById('detailBody').innerHTML='<div class="hpr-detail-status"><b>LIVE</b></div><div class="section"><div class="kv"><span>ICAO</span><span>888002</span></div></div>'});await expect(page.locator('#hprReplayDock')).toBeHidden();expect(await page.evaluate(()=>window.HPREdgeReplay.state().activeId)).toBe(null);expect(errors).toEqual([]);await browser.close()});
