'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const trafficCode=fs.readFileSync('hpr/edge/ui/edge-traffic-enrich.js','utf8');
const detailCode=fs.readFileSync('hpr/edge/ui/edge-detail-cards.js','utf8');
const window={HPR_CONFIG:{trafficApi:'/api/traffic'}};
const document={addEventListener:()=>{},querySelector:()=>null,querySelectorAll:()=>[],head:{appendChild:()=>{}},createElement:()=>({})};
const context={window,document,console,Object,Array,Map,JSON,Date,fetch:async()=>({ok:false}),queueMicrotask:()=>{},MutationObserver:function(){},encodeURIComponent,setInterval:()=>1};
vm.createContext(context);vm.runInContext(trafficCode,context,{filename:'edge-traffic-enrich.js'});
assert(window.HPREdgeTraffic,'traffic enrichment export missing');
assert.strictEqual(window.HPREdgeTraffic.base,'/api/traffic');
const ac=window.HPREdgeTraffic.unwrapAircraft({response:{aircraft:{mode_s:'888123',manufacturer:'Airbus'}}});
assert.strictEqual(ac.mode_s,'888123');assert.strictEqual(ac.manufacturer,'Airbus');
const rt=window.HPREdgeTraffic.unwrapRoute({response:{flightroute:{callsign:'VJC123'}}});
assert.strictEqual(rt.callsign,'VJC123');
vm.runInContext(detailCode,context,{filename:'edge-detail-cards.js'});
assert(window.HPREdgeDetailCards,'detail cards export missing');
assert.strictEqual(typeof window.HPREdgeDetailCards.decorate,'function');
console.log('edge traffic/detail runtime smoke PASS');
