'use strict';
const {test,expect,chromium}=require('@playwright/test');
const http=require('http'),fs=require('fs'),path=require('path');
const ROOT=path.resolve(__dirname,'../hpr/edge/ui');let server,baseURL,counts;
const scripts=['edge-g5-detail.js','edge-g6-detail-layout.js','edge-g7-enrich.js'];
test.beforeAll(async()=>{counts={aircraft:0,route:0,photo:0};server=http.createServer((req,res)=>{const p=req.url.replace(/^\//,'');if(scripts.includes(p)){res.setHeader('content-type','application/javascript; charset=utf-8');return res.end(fs.readFileSync(path.join(ROOT,p)))}if(req.url==='/api/traffic/v0/aircraft/888001'){counts.aircraft++;res.setHeader('content-type','application/json');return res.end(JSON.stringify({response:{aircraft:{manufacturer:'Airbus',model:'A321-272N',registered_owner:'Vietnam Airlines'}}}))}if(req.url==='/api/traffic/v0/callsign/HPR123'){counts.route++;res.setHeader('content-type','application/json');return res.end(JSON.stringify({response:{flightroute:{origin:{icao_code:'VVNB',name:'Noi Bai'},destination:{icao_code:'VVTS',name:'Tan Son Nhat'},airline:{name:'Vietnam Airlines',icao:'HVN'}}}}))}if(req.url==='/api/photo/hex/888001'){counts.photo++;res.setHeader('content-type','application/json');return res.end(JSON.stringify({photos:[{thumbnail:{src:'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw=='},photographer:'HPR Test'}]}))}if(req.url.startsWith('/api/')){res.statusCode=503;return res.end('{}')}res.setHeader('content-type','text/html; charset=utf-8');res.end(`<!doctype html><html><head>${scripts.map(x=>`<script src="/${x}"></script>`).join('')}</head><body><div id="detailBody"></div></body></html>`)});await new Promise(r=>server.listen(0,'127.0.0.1',r));baseURL=`http://127.0.0.1:${server.address().port}`});
test.afterAll(async()=>{if(server)await new Promise(r=>server.close(r))});
const html='<div class="detail-head"><span class="plane-big"><svg></svg></span><span class="detail-title"><b>HPR123</b><small>VN-A888 · A321</small></span></div><div class="metric-grid"></div><div class="section"><h3>Identity</h3><div class="kv"><span>ICAO</span><span>888001</span><span>Callsign</span><span>HPR123</span><span>Squawk</span><span>1200</span><span>Source</span><span>ADS-B</span></div></div>';
test('G7 enriches selected aircraft once and survives rerender',async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome',args:['--no-sandbox']});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto(baseURL,{waitUntil:'domcontentloaded'});await page.waitForTimeout(50);expect(counts).toEqual({aircraft:0,route:0,photo:0});await page.evaluate(v=>document.getElementById('detailBody').innerHTML=v,html);await expect.poll(()=>page.locator('[data-hpr-operator]').textContent()).toBe('Vietnam Airlines');await expect(page.locator('[data-hpr-route-from]')).toHaveText('VVNB');await expect(page.locator('[data-hpr-route-to]')).toHaveText('VVTS');await expect(page.locator('[data-hpr-airframe]')).toHaveText('Airbus A321-272N');await expect(page.locator('[data-hpr-photo-slot]')).not.toHaveAttribute('hidden','');await expect(page.locator('[data-hpr-photo-slot] img')).toHaveAttribute('loading','lazy');expect(counts).toEqual({aircraft:1,route:1,photo:1});await page.evaluate(v=>document.getElementById('detailBody').innerHTML=v,html);await expect(page.locator('[data-hpr-operator]')).toHaveText('Vietnam Airlines');await page.waitForTimeout(100);expect(counts).toEqual({aircraft:1,route:1,photo:1});expect(errors).toEqual([]);await browser.close()});
