'use strict';
const {test,expect,chromium}=require('@playwright/test');
const http=require('http'),fs=require('fs'),path=require('path');
const ROOT=path.resolve(__dirname,'../hpr/edge/ui');let server,baseURL;
test.beforeAll(async()=>{server=http.createServer((req,res)=>{if(req.url==='/edge-g17-vn-labels.js'){res.setHeader('content-type','application/javascript; charset=utf-8');return res.end(fs.readFileSync(path.join(ROOT,'edge-g17-vn-labels.js')))}res.setHeader('content-type','text/html; charset=utf-8');res.end(`<!doctype html><html data-theme="dark"><head><script>
const listeners={},sources=new Map(),layers=new Map(),filters=new Map();
function baseStyle(){layers.clear();layers.set('place-city',{id:'place-city',type:'symbol',layout:{'text-field':['get','name']}});filters.set('place-city',['==',['get','class'],'city'])}
baseStyle();globalThis.__g17={listeners,sources,layers,filters,baseStyle};
globalThis.HPREdgeMap={getStyle:()=>({layers:[...layers.values()]}),getFilter:id=>filters.get(id)||null,setFilter:(id,f)=>filters.set(id,f),getSource:id=>sources.get(id),addSource:(id,s)=>sources.set(id,{data:s.data,setData(d){this.data=d}}),getLayer:id=>layers.get(id),addLayer:(l,before)=>{l.__before=before;layers.set(l.id,l)},setLayoutProperty:(id,k,v)=>{const l=layers.get(id);l.layout||(l.layout={});l.layout[k]=v},on:(ev,cb)=>listeners[ev]=cb,isStyleLoaded:()=>true};
</script><script src="/edge-g17-vn-labels.js"></script></head><body></body></html>`)});await new Promise(r=>server.listen(0,'127.0.0.1',r));baseURL=`http://127.0.0.1:${server.address().port}`});
test.afterAll(async()=>{if(server)await new Promise(r=>server.close(r))});
test('G17 suppresses alternate labels and restores Vietnamese labels after style reload',async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome',args:['--no-sandbox']});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto(baseURL,{waitUntil:'domcontentloaded'});let state=await page.evaluate(()=>({filter:__g17.filters.get('place-city'),names:__g17.sources.get('hpr-vn-archipelago-labels').data.features.map(f=>f.properties.name),layer:__g17.layers.get('hpr-vn-archipelago-labels')}));expect(JSON.stringify(state.filter).toLowerCase()).toContain('sansha');expect(JSON.stringify(state.filter).toLowerCase()).toContain('nansha');expect(state.names).toEqual(['HOÀNG SA','TRƯỜNG SA']);expect(state.layer.minzoom).toBe(4);expect(state.layer.layout['text-size']).toEqual(['interpolate',['linear'],['zoom'],4,9,9,12]);expect(state.layer.layout['text-allow-overlap']).toBe(true);await page.evaluate(()=>{__g17.sources.clear();__g17.baseStyle();__g17.listeners['style.load']()});state=await page.evaluate(()=>({filter:__g17.filters.get('place-city'),names:__g17.sources.get('hpr-vn-archipelago-labels').data.features.map(f=>f.properties.name),layer:__g17.layers.get('hpr-vn-archipelago-labels')}));expect(JSON.stringify(state.filter).toLowerCase()).toContain('sansha');expect(state.names).toEqual(['HOÀNG SA','TRƯỜNG SA']);expect(state.layer).toBeTruthy();expect(errors).toEqual([]);await browser.close()});
