(()=>{'use strict';
const FE_VERSION='4.7.2';
const FE_BUILD='260912.2';
const F={HEX:0,CLASS:1,FLAGS:2,CALL:3,LAT:4,LON:5,BARO:6,GEOM:7,GS:8,TRACK:9,BARO_RATE:10,GEOM_RATE:11,SQUAWK:12,CATEGORY:13,EMERGENCY:14,SEEN_POS:15,SEEN:16,RSSI:17,REG:18,TYPE:19,DB:20,MSGS:21};
const FLAG={GROUND:1,ALERT:2,SPI:4,NON_ICAO:8,POSITION:16,MLAT:32};
const SOURCE_NAMES=['ADS-B','ADS-B NT','ADS-R','TIS-B','ADS-C','MLAT','Other','Mode-S','ADS-B other','ADS-R other','TIS-B track','TIS-B other','Mode-A','Unknown'];
const ALT_COLOR_EXPR=['interpolate',['linear'],['coalesce',['get','alt'],0],0,'#2ecc71',5000,'#3498db',15000,'#f1c40f',30000,'#e67e22',42000,'#e74c3c'];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,d=0)=>v==null||Number.isNaN(Number(v))?'—':Number(v).toLocaleString(undefined,{minimumFractionDigits:d,maximumFractionDigits:d});
const age=v=>v==null?'—':v<60?`${Number(v).toFixed(v<10?1:0)} s`:`${Math.floor(v/60)}m ${Math.round(v%60)}s`;
const altitude=a=>a.ground?'GROUND':a.baro==null?'—':`${fmt(a.baro)} ft`;
const method=a=>a.mlat?'MLAT':(SOURCE_NAMES[a.cls]||'Unknown');
const label=a=>a.callsign||a.registration||a.id.toUpperCase();
const statusColor=s=>s==='live'?'var(--live)':s==='aging'?'var(--aging)':'var(--stale)';
function altColor(v){v=Number(v||0);const stops=[[0,[46,204,113]],[5000,[52,152,219]],[15000,[241,196,15]],[30000,[230,126,34]],[42000,[231,76,60]]];for(let i=0;i<stops.length-1;i++){if(v<=stops[i+1][0]){const [a,c0]=stops[i],[b,c1]=stops[i+1],t=Math.max(0,Math.min(1,(v-a)/(b-a)));return`rgb(${c0.map((x,j)=>Math.round(x+(c1[j]-x)*t)).join(',')})`}}return'rgb(231,76,60)'}

let aircraft=[],receiver=null,stats=null,lastEnvelope=null,lastGood=0,lastCount=null,lastCountTs=null,msgRate=0,selected=null,tab='visible',polling=false,firstFit=true;
let map=null,mapReady=false,handlersBound=false,labelsOn=true,trailOn=true;
const histories=new Map();
let spriteMeta=null,spriteImage=null,spriteSuffix='';
const themeKey='hpr-atlas-edge-theme';
let theme=localStorage.getItem(themeKey)||'dark';
document.documentElement.dataset.theme=theme;

function decode(r){
  const flags=Number(r[F.FLAGS]||0),seen=Number(r[F.SEEN]??999),type=String(r[F.TYPE]||'').trim().toUpperCase();
  const category=typeof r[F.CATEGORY]==='string'&&/^[ABC]\d$/i.test(r[F.CATEGORY])?String(r[F.CATEGORY]).toUpperCase():'';
  const shape=typeof resolveIcon==='function'?resolveIcon({t:type,category}):'unknown';
  return {id:String(r[F.HEX]||''),cls:Number(r[F.CLASS]??13),flags,callsign:r[F.CALL]||null,
    coord:r[F.LAT]!=null&&r[F.LON]!=null?[Number(r[F.LON]),Number(r[F.LAT])]:null,
    baro:r[F.BARO],geom:r[F.GEOM],gs:r[F.GS],track:r[F.TRACK],baroRate:r[F.BARO_RATE],geomRate:r[F.GEOM_RATE],
    squawk:r[F.SQUAWK],category:r[F.CATEGORY],emergency:r[F.EMERGENCY],seenPos:r[F.SEEN_POS],seen,rssi:r[F.RSSI],
    registration:r[F.REG],type,db:r[F.DB],messages:r[F.MSGS],shape,
    ground:!!(flags&FLAG.GROUND),mlat:!!(flags&FLAG.MLAT),alert:!!(flags&FLAG.ALERT),spi:!!(flags&FLAG.SPI),position:!!(flags&FLAG.POSITION),
    status:seen<=10?'live':seen<=30?'aging':'stale'};
}
function rememberTrails(next){
  for(const a of next){if(!a.coord)continue;let h=histories.get(a.id);if(!h){h=[];histories.set(a.id,h)}const last=h[h.length-1];if(!last||Math.abs(last[0]-a.coord[0])>.00005||Math.abs(last[1]-a.coord[1])>.00005){if(last&&(Math.abs(last[0]-a.coord[0])>2||Math.abs(last[1]-a.coord[1])>2))h.length=0;h.push(a.coord);if(h.length>120)h.splice(0,h.length-120)}}
  const live=new Set(next.map(a=>a.id));for(const id of histories.keys())if(!live.has(id)&&histories.get(id).length>120)histories.delete(id);
}
function filtered(){
  const q=$('#search').value.trim().toLowerCase();
  return aircraft.filter(a=>{if(tab==='airborne'&&a.ground)return false;if(tab==='ground'&&!a.ground)return false;if(tab==='mlat'&&!a.mlat)return false;if(tab==='stale'&&a.status==='live')return false;if(!q)return true;return[a.id,a.callsign,a.registration,a.type].some(v=>String(v||'').toLowerCase().includes(q))}).sort((a,b)=>a.seen-b.seen||label(a).localeCompare(label(b)));
}
function renderChips(){const live=aircraft.filter(a=>a.status==='live').length,mlat=aircraft.filter(a=>a.mlat).length,ground=aircraft.filter(a=>a.ground).length;$('#chips').innerHTML=`<span class="chip" style="--chip:var(--air)"><i></i><span>Aircraft</span><b>${aircraft.length}</b></span><span class="chip" style="--chip:var(--live)"><i></i><span>Live</span><b>${live}</b></span><span class="chip" style="--chip:var(--accent)"><i></i><span>MLAT</span><b>${mlat}</b></span><span class="chip" style="--chip:var(--stale)"><i></i><span>Ground</span><b>${ground}</b></span><span class="chip" style="--chip:var(--accent)"><i></i><span>msg/s</span><b>${fmt(msgRate)}</b></span>`}
function rowHtml(a){const color=altColor(a.baro),sub=[a.registration||a.id.toUpperCase(),a.type||a.shape,age(a.seen)].filter(Boolean).join(' · ');return `<button class="entity-row ${selected===a.id?'selected':''}" data-id="${esc(a.id)}"><span class="entity-status" style="--st:${statusColor(a.status)}"></span><span class="entity-icon" style="--hdg:${Number(a.track||0)}deg;--st:${statusColor(a.status)}"><canvas width="64" height="64" data-shape="${esc(a.shape)}" data-color="${esc(color)}"></canvas></span><span class="entity-main"><span class="entity-line"><span class="entity-name">${esc(label(a))}</span><span class="entity-method">${esc(method(a))}</span></span><span class="entity-meta"><span>${esc(sub)}</span></span></span><span class="entity-kpi"><b style="color:${color}">${esc(altitude(a))}</b><small>${a.gs==null?'—':fmt(a.gs)+' kt'}</small></span></button>`}
function renderList(){const rows=filtered();$('#listCount').textContent=`${rows.length} shown`;$('#airList').innerHTML=rows.length?rows.map(rowHtml).join(''):'<div class="empty">No aircraft match this view</div>';$$('#airList .entity-row').forEach(el=>el.onclick=()=>selectAircraft(el.dataset.id,true));paintDomSprites()}
function section(title,rows){return `<section class="section"><h3>${title}</h3>${rows.map(x=>`<div class="field"><span>${esc(x[0])}</span><b>${esc(x[1])}</b></div>`).join('')}</section>`}
function renderDetail(){const a=aircraft.find(x=>x.id===selected);if(!a){$('#detail').classList.remove('open');return}const color=altColor(a.baro),vr=a.baroRate==null?'—':`${a.baroRate>0?'+':''}${fmt(a.baroRate)} fpm`;$('#detail').classList.add('open');$('#detailBody').innerHTML=`<div class="detail-head"><span class="detail-icon" style="--hdg:${Number(a.track||0)}deg"><canvas width="96" height="96" data-shape="${esc(a.shape)}" data-color="${esc(color)}"></canvas></span><span class="detail-title"><b>${esc(label(a))}</b><small>${esc(a.registration||a.id.toUpperCase())} · ${esc(a.type||a.shape)}</small></span><button id="closeDetail" class="plain detail-close" aria-label="Close detail">×</button></div><div class="detail-status"><span class="trust-dot ${a.status==='live'?'':a.status}"></span><b>${a.status.toUpperCase()}</b><span>· ${esc(method(a))} · position ${age(a.seenPos)}</span></div><div class="motion"><div class="metric"><b style="color:${color}">${esc(altitude(a))}</b><small>Altitude</small></div><div class="metric"><b>${a.gs==null?'—':fmt(a.gs,1)+' kt'}</b><small>Ground speed</small></div><div class="metric"><b>${a.track==null?'—':fmt(a.track,1)+'°'}</b><small>Track</small></div></div><div class="detail-scroll">${section('Identity',[['ICAO',a.id.toUpperCase()],['Callsign',a.callsign||'—'],['Registration',a.registration||'—'],['Type',a.type||'—'],['Sprite',a.shape],['Squawk',a.squawk||'—']])}${section('Telemetry',[['Vertical rate',vr],['Geom altitude',a.geom==null?'—':fmt(a.geom)+' ft'],['Geom rate',a.geomRate==null?'—':fmt(a.geomRate)+' fpm'],['RSSI',a.rssi==null?'—':fmt(a.rssi,1)+' dBFS'],['Messages',fmt(a.messages)],['Seen',age(a.seen)]])}${section('Position',[['Latitude',a.coord?fmt(a.coord[1],6):'—'],['Longitude',a.coord?fmt(a.coord[0],6):'—'],['State',a.ground?'GROUND':'AIRBORNE'],['Alert',a.alert?'YES':'NO'],['Reliable position',a.position?'YES':'NO']])}</div><div class="detail-actions"><button id="followBtn" class="action">Center</button><button id="copyBtn" class="action">Copy ICAO</button></div>`;$('#closeDetail').onclick=()=>{selected=null;renderList();renderDetail();updateMap()};$('#followBtn').onclick=()=>focusAircraft(a);$('#copyBtn').onclick=()=>navigator.clipboard?.writeText(a.id.toUpperCase());paintDomSprites()}
function renderReceiver(){selected=null;renderList();updateMap();$('#detail').classList.add('open');const version=receiver?.version||'readsb',refresh=receiver?.refresh||1000;$('#detailBody').innerHTML=`<div class="detail-head"><span class="detail-icon" style="color:var(--accent);font-size:28px">⌁</span><span class="detail-title"><b>Local Source</b><small>${esc(version)}</small></span><button id="closeDetail" class="plain detail-close">×</button></div><div class="detail-status"><span class="trust-dot"></span><b>ONLINE</b><span>· AirWire v${lastEnvelope?.[0]||1}</span></div><div class="motion"><div class="metric"><b>${aircraft.length}</b><small>Aircraft</small></div><div class="metric"><b>${fmt(msgRate)}</b><small>msg/s</small></div><div class="metric"><b>${fmt(refresh)}</b><small>refresh ms</small></div></div><div class="detail-scroll">${section('Capabilities',[['readsb',receiver?.readsb?'YES':'—'],['DB server',receiver?.dbServer?'YES':'—'],['binCraft',receiver?.binCraft?'YES':'—'],['zstd',receiver?.zstd?'YES':'—'],['Total messages',fmt(lastEnvelope?.[2])],['Stats endpoint',stats?'LIVE':'—']])}${section('Frontend',[['FE',FE_VERSION],['Build',FE_BUILD],['Renderer','Atlas SDF 81-shape'],['Basemap',theme==='dark'?'HPR Dark Minimal':'HPR Light Minimal']])}</div>`;$('#closeDetail').onclick=()=>$('#detail').classList.remove('open')}

function fc(){return{type:'FeatureCollection',features:aircraft.filter(a=>a.coord).map(a=>({type:'Feature',id:a.id,geometry:{type:'Point',coordinates:a.coord},properties:{id:a.id,label:label(a),callsign:a.callsign||'',type:a.type||'',shape:a.shape||'unknown',track:Number(a.track||0),alt:Number(a.baro||0),gs:Number(a.gs||0),selected:a.id===selected?1:0,status:a.status,mlat:a.mlat?1:0}}))}}
function trailFc(){const a=aircraft.find(x=>x.id===selected),h=a?histories.get(a.id):null;return{type:'FeatureCollection',features:h&&h.length>1?[{type:'Feature',properties:{},geometry:{type:'LineString',coordinates:h}}]:[]}}
function installAircraftLayers(){if(!map||!map.isStyleLoaded())return;if(!map.getSource('aircraft'))map.addSource('aircraft',{type:'geojson',data:fc()});if(!map.getSource('selected-trail'))map.addSource('selected-trail',{type:'geojson',data:trailFc()});if(!map.getLayer('selected-trail'))map.addLayer({id:'selected-trail',type:'line',source:'selected-trail',layout:{visibility:trailOn?'visible':'none'},paint:{'line-color':'#00e5ff','line-width':2,'line-opacity':.7,'line-dasharray':[2,1]}});if(!map.getLayer('ac-dots'))map.addLayer({id:'ac-dots',type:'circle',source:'aircraft',maxzoom:5,paint:{'circle-radius':['interpolate',['linear'],['zoom'],2,1.5,4,3,5,4],'circle-color':ALT_COLOR_EXPR,'circle-opacity':.9}});if(!map.getLayer('ac-halo'))map.addLayer({id:'ac-halo',type:'circle',source:'aircraft',minzoom:5,paint:{'circle-radius':['case',['==',['get','selected'],1],18,0],'circle-color':'rgba(0,0,0,0)','circle-stroke-width':['case',['==',['get','selected'],1],2,0],'circle-stroke-color':'#00e5ff','circle-blur':.15}});const addIcons=()=>{if(!map.getLayer('ac-icons'))map.addLayer({id:'ac-icons',type:'symbol',source:'aircraft',minzoom:5,layout:{'icon-image':['coalesce',['get','shape'],'unknown'],'icon-size':['interpolate',['linear'],['zoom'],5,.5,8,.7,12,.9,15,1.0],'icon-rotate':['coalesce',['get','track'],0],'icon-rotation-alignment':'map','icon-allow-overlap':true,'icon-ignore-placement':true,'icon-padding':0},paint:{'icon-color':ALT_COLOR_EXPR}});if(!map.getLayer('ac-labels'))map.addLayer({id:'ac-labels',type:'symbol',source:'aircraft',minzoom:7,layout:{'text-field':['get','label'],'text-size':10,'text-offset':[0,2.1],'text-anchor':'top','text-allow-overlap':false,'visibility':labelsOn?'visible':'none'},paint:{'text-color':theme==='dark'?'#d7e8f8':'#294653','text-halo-color':theme==='dark'?'#07121e':'#fffef9','text-halo-width':1.2}});bindMapHandlers();updateMap()};registerSpriteImages(addIcons)}
function updateMap(){if(!mapReady||!map.getSource('aircraft'))return;map.getSource('aircraft').setData(fc());map.getSource('selected-trail')?.setData(trailFc())}
function bindMapHandlers(){if(handlersBound)return;handlersBound=true;const layers=['ac-icons','ac-dots'];for(const layer of layers){map.on('click',layer,e=>{const id=e.features?.[0]?.properties?.id;if(id)selectAircraft(String(id),false)});map.on('mouseenter',layer,e=>{map.getCanvas().style.cursor='pointer';showPopup(e)});map.on('mousemove',layer,showPopup);map.on('mouseleave',layer,()=>{map.getCanvas().style.cursor='';popup.remove()})}}
const popup=new maplibregl.Popup({closeButton:false,closeOnClick:false,offset:14});
function showPopup(e){const f=e.features?.[0];if(!f)return;const p=f.properties,alt=Number(p.alt)?`${Number(p.alt).toLocaleString()} ft`:'—',gs=Number(p.gs)?`${Math.round(Number(p.gs))} kt`:'—';popup.setLngLat(f.geometry.coordinates).setHTML(`<div class="pop-title">${esc(p.label||p.id)}</div><div class="pop-line"><span>${esc(p.type||p.id)}</span><b>${esc(alt)}</b></div><div class="pop-line"><span>Ground speed</span><b>${esc(gs)}</b></div>`).addTo(map)}
function fitAll(){if(!mapReady)return;const pts=aircraft.filter(a=>a.coord);if(!pts.length)return;const b=new maplibregl.LngLatBounds();pts.forEach(a=>b.extend(a.coord));const mobile=innerWidth<=700;map.fitBounds(b,{padding:{top:60,bottom:mobile?100:60,left:mobile?40:380,right:mobile?40:380},maxZoom:9,duration:450})}
function focusAircraft(a){if(a?.coord)map.flyTo({center:a.coord,zoom:Math.max(map.getZoom(),8),duration:450})}
function selectAircraft(id,fly){selected=id;renderList();renderDetail();updateMap();const a=aircraft.find(x=>x.id===id);if(fly&&a)focusAircraft(a)}

async function loadSpritePack(){spriteSuffix=devicePixelRatio>=2?'@2x':'';try{const [meta,img]=await Promise.all([fetch(`./sprite${spriteSuffix}.json`,{cache:'force-cache'}).then(r=>{if(!r.ok)throw Error(r.status);return r.json()}),new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=`./sprite${spriteSuffix}.png`})]);spriteMeta=meta;spriteImage=img;if(mapReady)registerSpriteImages();paintDomSprites()}catch(e){console.error('Atlas sprite load failed',e)}}
function registerSpriteImages(cb){if(!map||!spriteImage||!spriteMeta){if(cb)cb();return}const c=document.createElement('canvas');c.width=spriteImage.width;c.height=spriteImage.height;const cx=c.getContext('2d',{willReadFrequently:true});cx.drawImage(spriteImage,0,0);for(const [name,m]of Object.entries(spriteMeta)){if(map.hasImage(name))continue;const d=cx.getImageData(m.x,m.y,m.width,m.height);map.addImage(name,{width:m.width,height:m.height,data:d.data},{sdf:true,pixelRatio:m.pixelRatio})}if(cb)cb()}
function paintCanvas(canvas){if(!spriteMeta||!spriteImage)return;const m=spriteMeta[canvas.dataset.shape]||spriteMeta.unknown;if(!m)return;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);const pad=4,size=Math.min(canvas.width,canvas.height)-pad*2;ctx.drawImage(spriteImage,m.x,m.y,m.width,m.height,pad,pad,size,size);ctx.globalCompositeOperation='source-in';ctx.fillStyle=canvas.dataset.color||'#f2cf5b';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.globalCompositeOperation='source-over'}
function paintDomSprites(){$$('canvas[data-shape]').forEach(paintCanvas)}

function setConnected(ok){const el=$('#connection');el.classList.toggle('offline',!ok);el.querySelector('span:last-child').textContent=ok?`LIVE · ${aircraft.length}`:'AirWire offline'}
async function loadReceiver(){try{const r=await fetch('/api/readsb/receiver.json',{cache:'no-store'});if(r.ok)receiver=await r.json()}catch(_){}}
async function loadStats(){try{const r=await fetch('/data/stats.json',{cache:'no-store'});if(r.ok)stats=await r.json()}catch(_){}}
async function tick(){if(polling)return;polling=true;try{const r=await fetch('/api/air/v1',{cache:'no-store'});if(!r.ok)throw Error(r.status);const env=await r.json();if(!Array.isArray(env)||env[0]!==1||!Array.isArray(env[3]))throw Error('bad AirWire');lastEnvelope=env;const next=env[3].map(decode);rememberTrails(next);aircraft=next;lastGood=Date.now();setConnected(true);const now=Date.now(),count=Number(env[2]||0);if(lastCount!=null&&count>=lastCount)msgRate=(count-lastCount)/Math.max((now-lastCountTs)/1000,.001);lastCount=count;lastCountTs=now;if(selected&&!aircraft.some(a=>a.id===selected))selected=null;renderChips();renderList();renderDetail();updateMap();if(firstFit&&aircraft.some(a=>a.coord)){firstFit=false;fitAll()}}catch(e){if(Date.now()-lastGood>3500)setConnected(false)}finally{polling=false}}

function setTheme(next){theme=next;localStorage.setItem(themeKey,theme);document.documentElement.dataset.theme=theme;if(map)map.setStyle(`./mapstyles/${theme==='dark'?'dark':'light'}-minimal.json`)}
function initMap(){map=new maplibregl.Map({container:'map',style:`./mapstyles/${theme==='dark'?'dark':'light'}-minimal.json`,center:[106.375,20.95],zoom:6.3,attributionControl:false});map.addControl(new maplibregl.NavigationControl({visualizePitch:true}),'top-right');map.addControl(new maplibregl.AttributionControl({compact:true}),'bottom-right');map.on('style.load',()=>{mapReady=true;try{map.setProjection({type:'globe'})}catch(_){}installAircraftLayers()});map.on('mousemove',e=>{$('#coordDisplay').textContent=`${e.lngLat.lat.toFixed(4)}°N ${e.lngLat.lng.toFixed(4)}°E · Z${map.getZoom().toFixed(1)} · FE ${FE_VERSION}`})}

$('#search').oninput=renderList;$('#airBtn').onclick=()=>{const p=$('#collection');p.classList.toggle('open');$('#airBtn').classList.toggle('on',p.classList.contains('open'));$('#airBtn').setAttribute('aria-expanded',String(p.classList.contains('open')))};$('#receiverBtn').onclick=renderReceiver;$('#fitBtn').onclick=fitAll;$('#closeList').onclick=()=>{$('#collection').classList.remove('open');$('#airBtn').classList.remove('on');$('#airBtn').setAttribute('aria-expanded','false')};
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('on'));b.classList.add('on');tab=b.dataset.tab;renderList()});
$('#themeBtn').onclick=()=>setTheme(theme==='dark'?'light':'dark');$('#layersBtn').onclick=()=>{$('#layersPanel').classList.toggle('open');$('#layersBtn').classList.toggle('on',$('#layersPanel').classList.contains('open'))};$('#closeLayers').onclick=()=>{$('#layersPanel').classList.remove('open');$('#layersBtn').classList.remove('on')};
$('#labelsSwitch').onchange=e=>{labelsOn=e.target.checked;if(map?.getLayer('ac-labels'))map.setLayoutProperty('ac-labels','visibility',labelsOn?'visible':'none')};$('#trailSwitch').onchange=e=>{trailOn=e.target.checked;if(map?.getLayer('selected-trail'))map.setLayoutProperty('selected-trail','visibility',trailOn?'visible':'none')};
document.addEventListener('keydown',e=>{if(e.key==='Escape'){selected=null;$('#detail').classList.remove('open');$('#layersPanel').classList.remove('open');renderList();updateMap()}});

initMap();loadSpritePack();loadReceiver();loadStats();tick();setInterval(tick,1000);setInterval(loadReceiver,30000);setInterval(loadStats,10000);
})();
