(()=>{'use strict';
/* Real readsb trace/replay overlay. Never synthesizes trail points in the browser. */
const EMPTY={type:'FeatureCollection',features:[]};
let map=null,selected=null,tracePoints=[],traceGeo=EMPTY,replayId=0,replaySpeed=5,lastLoad=0;
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function captureMap(){if(!window.maplibregl?.Map||window.__HPR_MAP_CAPTURED)return;const Native=window.maplibregl.Map;window.maplibregl.Map=class extends Native{constructor(opts){super(opts);map=this;window.HPREdgeMap=this;this.on('style.load',()=>{ensureLayers();renderTrace()})}};window.__HPR_MAP_CAPTURED=true}
function pointGeo(p){return p?{type:'FeatureCollection',features:[{type:'Feature',properties:{alt:String(p.alt??''),gs:p.gs??'',track:p.track??''},geometry:{type:'Point',coordinates:[p.lon,p.lat]}}]}:EMPTY}
function traceToGeo(points){const lines=[];let line=[];for(const p of points){if((p.flags&2)&&line.length>1){lines.push(line);line=[]}line.push([p.lon,p.lat])}if(line.length>1)lines.push(line);return{type:'FeatureCollection',features:lines.map((coords,i)=>({type:'Feature',properties:{leg:i+1},geometry:{type:'LineString',coordinates:coords}}))}}
function ensureLayers(){if(!map||!map.isStyleLoaded())return;try{if(!map.getSource('hpr-readsb-trace'))map.addSource('hpr-readsb-trace',{type:'geojson',data:EMPTY});if(!map.getLayer('hpr-readsb-trace'))map.addLayer({id:'hpr-readsb-trace',type:'line',source:'hpr-readsb-trace',paint:{'line-color':'#00d8ff','line-width':['interpolate',['linear'],['zoom'],4,1.4,10,2.6],'line-opacity':.78}});if(!map.getSource('hpr-readsb-replay'))map.addSource('hpr-readsb-replay',{type:'geojson',data:EMPTY});if(!map.getLayer('hpr-readsb-replay'))map.addLayer({id:'hpr-readsb-replay',type:'circle',source:'hpr-readsb-replay',paint:{'circle-radius':8,'circle-color':'#ffffff','circle-stroke-color':'#00d8ff','circle-stroke-width':3}})}catch(e){console.warn('HPR trace layers',e)}}
function renderTrace(){ensureLayers();try{map?.getSource('hpr-readsb-trace')?.setData(traceGeo)}catch(_){}}
function setReplayPoint(p){ensureLayers();try{map?.getSource('hpr-readsb-replay')?.setData(pointGeo(p))}catch(_){}}
function traceUrl(id,kind){return`/data/traces/${id.slice(-2)}/trace_${kind}_${id}.json`}
async function getJson(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error(String(r.status));return r.json()}
function normalizeTrace(j){const base=Number(j?.timestamp||0);if(!base||!Array.isArray(j?.trace))return[];return j.trace.map(p=>({ts:base+Number(p?.[0]||0),lat:Number(p?.[1]),lon:Number(p?.[2]),alt:p?.[3],gs:p?.[4],track:p?.[5],flags:Number(p?.[6]||0),vr:p?.[7]})).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon))}
function mergePoints(parts){const m=new Map();for(const list of parts)for(const p of list)m.set(`${p.ts.toFixed(3)}:${p.lat.toFixed(5)}:${p.lon.toFixed(5)}`,p);return[...m.values()].sort((a,b)=>a.ts-b.ts)}
async function loadTrace(id,force=false){if(!id)return;if(!force&&id===selected&&Date.now()-lastLoad<12000)return;lastLoad=Date.now();selected=id;stopReplay(false);status('loading…');const results=await Promise.allSettled([getJson(traceUrl(id,'full')),getJson(traceUrl(id,'recent'))]);if(id!==selected)return;const good=results.filter(x=>x.status==='fulfilled').map(x=>normalizeTrace(x.value));tracePoints=mergePoints(good);traceGeo=traceToGeo(tracePoints);renderTrace();setReplayPoint(null);if(tracePoints.length){const mins=Math.max(0,(tracePoints.at(-1).ts-tracePoints[0].ts)/60);status(`${tracePoints.length} pts · ${mins.toFixed(mins<10?1:0)} min`);showPanel(true)}else{status('trace warming up');showPanel(true)}}
function status(text){const e=$('#hprTraceStatus');if(e)e.textContent=text}
function showPanel(on){const e=$('#hprTracePanel');if(e)e.hidden=!on}
function fitTrace(){if(!map||!tracePoints.length)return;const b=new maplibregl.LngLatBounds();tracePoints.forEach(p=>b.extend([p.lon,p.lat]));map.fitBounds(b,{padding:70,maxZoom:11,duration:400})}
function stopReplay(clear=true){if(replayId)cancelAnimationFrame(replayId);replayId=0;if(clear)setReplayPoint(null);const b=$('#hprReplayBtn');if(b)b.textContent='Replay'}
function startReplay(){if(tracePoints.length<2)return;stopReplay(false);const startWall=performance.now(),startTs=tracePoints[0].ts,endTs=tracePoints.at(-1).ts;let idx=0;const btn=$('#hprReplayBtn');if(btn)btn.textContent='Stop';function frame(now){if(!replayId)return;const target=startTs+(now-startWall)/1000*replaySpeed;while(idx+1<tracePoints.length&&tracePoints[idx+1].ts<=target)idx++;const p=tracePoints[idx];setReplayPoint(p);status(`REPLAY ${replaySpeed}× · ${idx+1}/${tracePoints.length}`);if(target>=endTs||idx>=tracePoints.length-1){stopReplay(false);status(`${tracePoints.length} pts · replay done`);return}replayId=requestAnimationFrame(frame)}replayId=requestAnimationFrame(frame)}
function toggleReplay(){replayId?stopReplay():startReplay()}
function buildPanel(){if($('#hprTracePanel'))return;const d=document.createElement('div');d.id='hprTracePanel';d.hidden=true;d.innerHTML=`<div class="hpr-trace-head"><b>READSB TRACE</b><span id="hprTraceStatus">—</span></div><div class="hpr-trace-actions"><button id="hprTraceFit">Fit trace</button><button id="hprReplayBtn">Replay</button><select id="hprReplaySpeed" title="Replay speed"><option value="1">1×</option><option value="5" selected>5×</option><option value="10">10×</option><option value="20">20×</option><option value="40">40×</option></select></div>`;document.body.appendChild(d);const st=document.createElement('style');st.textContent=`#hprTracePanel{position:fixed;z-index:74;right:10px;bottom:38px;width:230px;padding:9px;background:rgba(7,18,30,.94);border:1px solid #29465f;border-radius:8px;box-shadow:0 12px 28px rgba(0,0,0,.35);color:#eaf5ff;font:11px/1.3 Inter,system-ui,sans-serif;backdrop-filter:blur(12px)}#hprTracePanel[hidden]{display:none}.hpr-trace-head{display:flex;justify-content:space-between;gap:8px;align-items:center;margin-bottom:7px}.hpr-trace-head b{font-size:10px;letter-spacing:.55px;color:#59ddff}.hpr-trace-head span{color:#9ab0c5;font-variant-numeric:tabular-nums}.hpr-trace-actions{display:grid;grid-template-columns:1fr 1fr 58px;gap:5px}.hpr-trace-actions button,.hpr-trace-actions select{height:28px;border:1px solid #29465f;border-radius:5px;background:#0d1d2b;color:#eaf5ff;font:inherit}.hpr-trace-actions button:hover{border-color:#59ddff;color:#59ddff}@media(max-width:680px){#hprTracePanel{left:6px;right:6px;bottom:72px;width:auto}}`;document.head.appendChild(st);$('#hprTraceFit').onclick=fitTrace;$('#hprReplayBtn').onclick=toggleReplay;$('#hprReplaySpeed').onchange=e=>replaySpeed=Number(e.target.value)||5}
function selectedFromDom(){return document.querySelector('.row.selected')?.dataset?.id||null}
function watchSelection(){setInterval(()=>{const id=selectedFromDom();if(id&&id!==selected){selected=id;loadTrace(id,true)}else if(!id&&selected){selected=null;tracePoints=[];traceGeo=EMPTY;renderTrace();stopReplay();showPanel(false)}else if(id&&Date.now()-lastLoad>15000&&!replayId)loadTrace(id,true)},750)}
captureMap();document.addEventListener('DOMContentLoaded',()=>{buildPanel();watchSelection()});
})();
