(()=>{'use strict';
/* Real readsb trace only. Selecting an aircraft shows a conservative recent trace.
 * Never merge full+recent, never connect impossible jumps, and keep trace below aircraft.
 */
const EMPTY={type:'FeatureCollection',features:[]};
const MAX_TRACE_MIN=90,MAX_GAP_SEC=180,MAX_IMPLIED_KT=950;
let map=null,selected=null,points=[],traceGeo=EMPTY,lastLoad=0,traceVisible=false,dockOpen=false;
let replayId=0,replaySpeed=5,replayIndex=0,replayStartedWall=0,replayStartedTs=0;
const $=s=>document.querySelector(s),num=v=>Number.isFinite(Number(v))?Number(v):null;
const fmtTime=ts=>new Date(ts*1000).toISOString().slice(11,19);
function captureMap(){if(!window.maplibregl?.Map||window.__HPR_MAP_CAPTURED)return;const Native=window.maplibregl.Map;window.maplibregl.Map=class extends Native{constructor(opts){super(opts);map=this;window.HPREdgeMap=this;this.on('style.load',()=>{ensureLayers();renderTrace();setReplayPoint(dockOpen?points[replayIndex]||null:null)})}};window.__HPR_MAP_CAPTURED=true}
function pointGeo(p){return p?{type:'FeatureCollection',features:[{type:'Feature',properties:{alt:p.alt??'',gs:p.gs??'',track:p.track??''},geometry:{type:'Point',coordinates:[p.lon,p.lat]}}]}:EMPTY}
function haversineNm(a,b){const r=3440.065,toRad=x=>x*Math.PI/180,p1=toRad(a.lat),p2=toRad(b.lat),dp=toRad(b.lat-a.lat),dl=toRad(b.lon-a.lon),h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*r*Math.asin(Math.min(1,Math.sqrt(h)))}
function normalizeTrace(j){const base=Number(j?.timestamp||0);if(!base||!Array.isArray(j?.trace))return[];return j.trace.map(p=>({ts:base+Number(p?.[0]||0),lat:Number(p?.[1]),lon:Number(p?.[2]),alt:p?.[3],gs:p?.[4],track:p?.[5],flags:Number(p?.[6]||0),vr:p?.[7]})).filter(p=>Number.isFinite(p.ts)&&Number.isFinite(p.lat)&&Number.isFinite(p.lon)&&Math.abs(p.lat)<=90&&Math.abs(p.lon)<=180).sort((a,b)=>a.ts-b.ts)}
function sanitizeTrace(list,maxMinutes=MAX_TRACE_MIN){
  if(!list.length)return[];const newest=list.at(-1).ts,cut=newest-maxMinutes*60,src=list.filter(p=>p.ts>=cut),out=[];let prev=null;
  for(const p of src){let breakBefore=!!(p.flags&2);if(prev){const dt=p.ts-prev.ts;if(dt<=0)continue;if(dt>MAX_GAP_SEC)breakBefore=true;else{const nm=haversineNm(prev,p),kt=nm/(dt/3600);if(kt>MAX_IMPLIED_KT)breakBefore=true}}out.push({...p,breakBefore});prev=p}
  return out
}
function traceToGeo(list){const lines=[];let line=[];for(const p of list){if(p.breakBefore&&line.length){if(line.length>1)lines.push(line);line=[]}line.push([p.lon,p.lat])}if(line.length>1)lines.push(line);return{type:'FeatureCollection',features:lines.map((coordinates,i)=>({type:'Feature',properties:{leg:i+1},geometry:{type:'LineString',coordinates}}))}}
function ensureLayers(){if(!map?.isStyleLoaded?.())return;try{const before=map.getLayer('aircraft-symbol')?'aircraft-symbol':map.getLayer('aircraft-label')?'aircraft-label':undefined;if(!map.getSource('hpr-readsb-trace'))map.addSource('hpr-readsb-trace',{type:'geojson',data:EMPTY});if(!map.getLayer('hpr-readsb-trace'))map.addLayer({id:'hpr-readsb-trace',type:'line',source:'hpr-readsb-trace',paint:{'line-color':'#4fb8dd','line-width':['interpolate',['linear'],['zoom'],4,.8,10,1.6],'line-opacity':.52}},before);if(!map.getSource('hpr-readsb-replay'))map.addSource('hpr-readsb-replay',{type:'geojson',data:EMPTY});if(!map.getLayer('hpr-readsb-replay'))map.addLayer({id:'hpr-readsb-replay',type:'circle',source:'hpr-readsb-replay',paint:{'circle-radius':3,'circle-color':'#4fb8dd','circle-opacity':.65,'circle-stroke-width':0}},before)}catch(e){console.warn('HPR trace layers',e)}}
function renderTrace(){ensureLayers();try{map?.getSource('hpr-readsb-trace')?.setData(traceVisible?traceGeo:EMPTY)}catch(_){}}
function setReplayPoint(p){ensureLayers();try{map?.getSource('hpr-readsb-replay')?.setData(dockOpen&&p?pointGeo(p):EMPTY)}catch(_){}}
function traceUrl(id,kind){return`/data/traces/${id.slice(-2)}/trace_${kind}_${id}.json`}
async function getJson(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error(String(r.status));return r.json()}
async function loadBestTrace(id){let recent=[];try{recent=normalizeTrace(await getJson(traceUrl(id,'recent')))}catch(_){}if(recent.length>=2)return{kind:'recent',points:sanitizeTrace(recent)};let full=[];try{full=normalizeTrace(await getJson(traceUrl(id,'full')))}catch(_){}return{kind:'full',points:sanitizeTrace(full)}}
function status(t){const e=$('#hprTraceStatus');if(e)e.textContent=t}
function setDock(on){dockOpen=!!on;const e=$('#hprTraceDock');if(e)e.hidden=!dockOpen;if(dockOpen){traceVisible=true;renderTrace();syncTimeline();$('#detail')?.classList.remove('open');setReplayPoint(points[replayIndex]||null)}else stopReplay(true)}
async function loadTrace(id,force=false){if(!id)return;if(!force&&id===selected&&Date.now()-lastLoad<12000)return;selected=id;lastLoad=Date.now();stopReplay(false);status('loading…');const result=await loadBestTrace(id);if(id!==selected)return;points=result.points;traceGeo=traceToGeo(points);replayIndex=Math.max(0,points.length-1);traceVisible=true;renderTrace();setReplayPoint(null);syncTimeline();const legs=traceGeo.features.length;if(points.length){const mins=Math.max(0,(points.at(-1).ts-points[0].ts)/60);status(`${result.kind} · ${points.length} pts · ${legs} leg${legs===1?'':'s'} · ${mins.toFixed(mins<10?1:0)} min`)}else status('trace unavailable')}
function fitTrace(){if(!map||!points.length)return;const b=new maplibregl.LngLatBounds();points.forEach(p=>b.extend([p.lon,p.lat]));map.fitBounds(b,{padding:{top:70,bottom:110,left:90,right:90},maxZoom:11,duration:400})}
function syncTimeline(){const r=$('#hprTimeline'),start=$('#hprTimeStart'),now=$('#hprTimeNow'),end=$('#hprTimeEnd');if(!r)return;r.max=Math.max(0,points.length-1);r.value=Math.min(replayIndex,Math.max(0,points.length-1));r.disabled=points.length<2;if(points.length){start.textContent=fmtTime(points[0].ts);end.textContent=fmtTime(points.at(-1).ts);now.textContent=fmtTime(points[replayIndex]?.ts||points[0].ts)}else start.textContent=now.textContent=end.textContent='--:--:--'}
function scrub(i,center=false){if(!points.length)return;replayIndex=Math.max(0,Math.min(points.length-1,Number(i)||0));const p=points[replayIndex];setReplayPoint(p);syncTimeline();const alt=p.alt==='ground'?'GND':num(p.alt)!=null?`${Math.round(Number(p.alt)).toLocaleString()} ft`:'—',gs=num(p.gs)!=null?`${Math.round(Number(p.gs))} kt`:'—';status(`${fmtTime(p.ts)} · ${alt} · ${gs}`);if(center&&map)map.easeTo({center:[p.lon,p.lat],duration:120})}
function stopReplay(clear=false){if(replayId)cancelAnimationFrame(replayId);replayId=0;const b=$('#hprReplayBtn');if(b)b.textContent='▶ Play';if(clear)setReplayPoint(null)}
function startReplay(fromCurrent=true){if(points.length<2)return;traceVisible=true;renderTrace();setDock(true);stopReplay(false);if(!fromCurrent||replayIndex>=points.length-1)replayIndex=0;replayStartedWall=performance.now();replayStartedTs=points[replayIndex].ts;const btn=$('#hprReplayBtn');if(btn)btn.textContent='❚❚ Pause';function frame(now){if(!replayId)return;const target=replayStartedTs+(now-replayStartedWall)/1000*replaySpeed;while(replayIndex+1<points.length&&points[replayIndex+1].ts<=target)replayIndex++;scrub(replayIndex,false);if(replayIndex>=points.length-1){stopReplay(false);status('Replay complete');return}replayId=requestAnimationFrame(frame)}replayId=requestAnimationFrame(frame)}
function toggleReplay(){replayId?stopReplay(false):startReplay(true)}
function showFor(id){if(id&&id!==selected)return loadTrace(id,true);traceVisible=true;renderTrace();return Promise.resolve()}
function replayFor(id){if(id&&id!==selected){loadTrace(id,true).then(()=>{setDock(true);startReplay(false)})}else{setDock(true);startReplay(false)}}
function buildDock(){if($('#hprTraceDock'))return;const d=document.createElement('section');d.id='hprTraceDock';d.hidden=true;d.innerHTML=`<div class="hpr-trace-row"><div class="hpr-trace-title"><b>REPLAY</b><span id="hprTraceStatus">—</span></div><span id="hprTimeStart">--:--:--</span><input id="hprTimeline" type="range" min="0" max="0" value="0" step="1"><span id="hprTimeEnd">--:--:--</span><b id="hprTimeNow">--:--:--</b><button id="hprTraceFit">Fit</button><button id="hprReplayBtn">▶ Play</button><select id="hprReplaySpeed"><option value="1">1×</option><option value="5" selected>5×</option><option value="10">10×</option><option value="20">20×</option><option value="40">40×</option></select><button id="hprTraceClose">×</button></div>`;document.body.appendChild(d);const st=document.createElement('style');st.textContent=`#hprTraceDock{position:fixed;z-index:74;left:calc(86px + var(--list) + 12px);right:56px;bottom:10px;padding:7px 9px;background:color-mix(in srgb,var(--solid) 95%,transparent);border:1px solid var(--border);border-radius:8px;box-shadow:var(--shadow);backdrop-filter:blur(14px)}#hprTraceDock[hidden]{display:none}.hpr-trace-row{display:grid;grid-template-columns:minmax(115px,auto) 48px minmax(120px,1fr) 48px 54px auto auto auto auto;gap:6px;align-items:center}.hpr-trace-title{min-width:0}.hpr-trace-title b,.hpr-trace-title span{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.hpr-trace-title b{font-size:9px;color:var(--accent);letter-spacing:.6px}.hpr-trace-title span,#hprTraceDock>div>span{font-size:9px;color:var(--muted)}#hprTraceDock input{width:100%;accent-color:var(--accent)}#hprTraceDock button,#hprTraceDock select{height:27px;border:1px solid var(--border);border-radius:5px;background:var(--s2);color:var(--text);font:9px system-ui;padding:0 7px}#hprTimeNow{font:9px system-ui;color:var(--text2);text-align:right}@media(max-width:900px){#hprTraceDock{left:86px;right:10px}.hpr-trace-row{grid-template-columns:80px 1fr auto auto auto}.hpr-trace-row>#hprTimeStart,.hpr-trace-row>#hprTimeEnd,.hpr-trace-row>#hprTimeNow,.hpr-trace-row>#hprTraceFit{display:none}}@media(max-width:680px){#hprTraceDock{left:6px;right:6px;bottom:74px}.hpr-trace-row{grid-template-columns:68px 1fr auto auto}.hpr-trace-row>#hprReplaySpeed{display:none}}`;document.head.appendChild(st);$('#hprTraceFit').onclick=fitTrace;$('#hprReplayBtn').onclick=toggleReplay;$('#hprReplaySpeed').onchange=e=>replaySpeed=Number(e.target.value)||5;$('#hprTraceClose').onclick=()=>setDock(false);$('#hprTimeline').oninput=e=>{stopReplay(false);scrub(Number(e.target.value),false)};$('#hprTimeline').onchange=e=>scrub(Number(e.target.value),true)}
function selectedFromDom(){return document.querySelector('#airList .row.selected')?.dataset?.id||null}
function watchSelection(){setInterval(()=>{const id=selectedFromDom();if(id&&id!==selected){loadTrace(id,true)}else if(!id&&selected){selected=null;points=[];traceGeo=EMPTY;replayIndex=0;stopReplay(true);traceVisible=false;renderTrace();setDock(false)}else if(id&&Date.now()-lastLoad>15000&&!replayId)loadTrace(id,true)},700)}
captureMap();document.addEventListener('DOMContentLoaded',()=>{buildDock();watchSelection()},{once:true});window.addEventListener('hpr:history:show',e=>showFor(String(e.detail?.id||selectedFromDom()||'').toLowerCase()));window.addEventListener('hpr:history:replay',e=>replayFor(String(e.detail?.id||selectedFromDom()||'').toLowerCase()));
window.HPREdgeHistory=Object.freeze({show:()=>showFor(selectedFromDom()),play:()=>replayFor(selectedFromDom()),hide:()=>setDock(false),fit:fitTrace,state:()=>({selected,points:points.length,replayIndex,replaySpeed,dockOpen,traceVisible}),_test:{normalizeTrace,sanitizeTrace,traceToGeo,haversineNm}});
})();